version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8002:8002
    env_file:
      - ./.env.dev